version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.jmailen.kotlinter
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.2
  - dependency-name: org.jetbrains.kotlin.plugin.spring
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.springframework.boot:spring-boot-starter-test
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.fasterxml.jackson.module:jackson-module-kotlin
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: io.gitlab.arturbosch.detekt:detekt-formatting
    versions:
    - 1.15.0
  - dependency-name: io.gitlab.arturbosch.detekt
    versions:
    - 1.15.0
  - dependency-name: com.willowtreeapps.assertk:assertk-jvm
    versions:
    - "0.23"
